name: CI

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.0

    - name: Install dependencies
      run: make install

    - name: create enviroment
      run: cp .env.sample .env

    - name: Run Rubocop
      run: make lint

    - name: Run tests 
      run: make test
